#!/bin/zsh
#
#	= ^ . ^ =
#
# Author: Andrés Hernández - tonejito
#
# This software is released under the terms of the "BSD 2-Clause License",
# see LICENSE for more information.

VERSION="8.1.1"

set -x

# Open the app on a Rosetta 2 shell for x86_64 (Intel)
exec /usr/bin/arch -x86_64 /bin/zsh -c \
  "open /Applications/Cisco\ Packet\ Tracer\ ${VERSION}/Cisco\ Packet\ Tracer\ ${VERSION}.app"
